[build]
target = "ui/index.html"

[watch]
ignore = ["app"]

[serve]
port = 1420
open = false

[tools]
# https://github.com/dobicinaitis/tailwind-cli-extra
# specify the version of tailwind-cli-extra to use
tailwindcss = "2.8.2"
